version: '3'

services:
  # web:
  #   build: .
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app

  app:
    build: .
    command: python3 app.py
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
