version: '3'

services:
  app:
    build: .
    command: ["python3", "app.py"]
    # Usuń mapowanie portów dla aplikacji, aby nie wystawiała portu 5000 na zewnątrz
    # ports:
    #   - "5000:5000"
    # Opcjonalnie, dodaj wolumen do rozwoju
    volumes:
      - .:/usr/src/app # optional, useful for development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
